---
title: "Combined Code"
author: "Alexa Nava"
date: "2023-04-11"
output: word_document
---

All libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GenericML)
library(glmnet)
library(ggplot2)
library(tidyverse)
library(grf)
library(haven)
library(magrittr)
library(dplyr)
library(readxl)
library(tidyr)
```

Generic ML: Read data
```{r}
df <- read_excel("/Users/aloha/Desktop/Short_Baby_Yoda.xlsx")

df <- subset(df, select = -c(SameAddress,ExtraZip, Notes, Charges, High_Surname, High_Firstname, Race) )
df <- df[complete.cases(df),]
df[!is.na(df$IncarcerationStats),]

df$Combined_Race <- as.numeric(df$Combined_Race)
df$CurrentAge <- as.numeric(df$CurrentAge)
df$Gender <- as.numeric(df$Gender)
```

Generic ML: Dropping NA values for Z matrix
```{r}
df[!is.na(df$Combined_Race),]
df[!is.na(df$CurrentAge),]
df[!is.na(df$Gender),]

df[complete.cases(df$Combined_Race),]
df[complete.cases(df$CurrentAge),]
df[complete.cases(df$Gender),]

df <- na.omit(df)
```

Generic ML full code
```{r}
Z <- select(.data = df, Combined_Race, CurrentAge, Gender)
Y <- pull(df, IncarcerationStats)
D <- pull(df, AttendeeAngelTree)

Z <- as.matrix(Z)
Y <- as.numeric(Y)
D <- as.numeric(D)

# Just to start out, run linear model:
IncReg <- lm(IncarcerationStats ~ Combined_Race + CurrentAge + Gender, data=df)
summary(IncReg)

# Get propensity scores and put them into data frame:

glm_fit = glm(AttendeeAngelTree~Combined_Race, CurrentAge, Gender, data=df,
              family = binomial)
summary(glm_fit)

glm_probs = data.frame(propscores = predict(glm_fit, type="response"))
head("propscores")
propscores <- as.numeric("propscores")

# Set up the regression function:
X1 <- setup_X1(funs_Z = c("B", "S"), fixed_effects = NULL)

# Set up the standard errors (robust):
vcov <- setup_vcov(estimator = 'vcovHC')

# Tell it to use elastic net (=0.5) or lasso (=1.0):
learners <- c("mlr3::lrn('cv_glmnet', s = 'lambda.min', alpha = 0.5)")

genML <- GenericML(
  Z = Z, D = D, Y = Y, # observed data
  learners_GenericML = learners, # learners
  learner_propensity_score = "constant", # = 0.5 (RCT)
  num_splits = 100L, # number splits
  quantile_cutoffs = c(0.2, 0.4, 0.6, 0.8), # grouping
  significance_level = 0.05, # significance level
  X1_BLP = X1, X1_GATES = X1, # regression setup
  vcov_BLP = vcov, vcov_GATES = vcov, # covariance setup
  parallel = TRUE, num_cores = 6L, # parallelization
  Z_CLAN = Z,
  seed = 1234567) # RNG seed

summary(genML)

# Now getting Best Linear Predictor and Significance of HTEs:
results_BLP <- get_BLP(genML, plot = TRUE)
results_BLP # print & plot method
plot(results_BLP) # plot method

# Obtain Sorted Group Average Treatment Effects (GATES):
results_GATES <- get_GATES(genML, plot = TRUE)
results_GATES

## random graphs
#years attended and number of charges
ggplot(
  data = df,
  mapping = aes(x = NumberCharges, y = YearsAttended, color = AttendeeAngelTree)
) +
  geom_point()

#summary of sample's current age
ggplot(df, aes(x = CurrentAge)) +
  geom_histogram(binwidth = 0.5)
```

LASSO: Reading in
```{r}
df <- read_excel("/Users/aloha/Desktop/Short_Baby_Yoda.xlsx")

df <- subset(df, select = -c(SameAddress,ExtraZip, Notes, Charges, High_Surname, High_Firstname, Race) )

df$Gender <- as.numeric(df$Gender)

df <- df[complete.cases(df),]

variables <- c("Age_Start_Program", "AgeEligible",
        "CodedCharges", "Combined_Race", "CurrentAge", "Gender", 
        "YearsAttended", "YearStart", "Attendee/Angel Tree", "IncarcerationStats")

df <- df[covariates_names]


#save the data
write.table(df, "numericnoNA.csv", file = '/Users/aloha/Desktop/Race', row.names = FALSE, )

```

LASSO Code
```{r}
#omit NA variables in dataset & take out columns that include NA that would screw everything up


#Make covariates numeric
AgeEligible <- as.numeric
Assigned_Race_Surname <- as.numeric
CodedCharges <- as.numeric
Combined_Race <- as.numeric
CurrentAge <- as.numeric

Jail <- as.numeric
NumberCharges <- as.numeric
Prison <- as.numeric
YearsAttended <- as.numeric
YearStart <- as.numeric

# Extract covariates
covariates_names <- c("Age_Start_Program", "AgeEligible",
                      "CodedCharges", "Combined_Race", "CurrentAge", "Gender",
                      "YearsAttended", "YearStart", "AttendeeAngelTree")
X <- df[covariates_names]
Y <- df$IncarcerationStats
X <- scale(X) 
Y <- scale(Y) 



cv.lasso <- cv.glmnet(x = X, y = Y, family = "multinomial", nfolds = 20, alpha = 1)
plot(cv.lasso)

lasso_model <- glmnet(x = X, y = Y, family = "multinomial", alpha = 1, lamda = cv.lasso$lamda$min)
lasso_model$beta

coef(lasso_model,s=1)

plot(lasso_model, xvar = "lambda", label = TRUE)



colSums(is.na(X))

## residual bootstrap Lasso
bootLasso <- function(x, y, B = 500, type.boot = "residual", alpha = 0.05, 
                                             cv.method = "cv", nfolds = 10, foldid, cv.OLS = FALSE, tau = 0, 
                                             parallel = FALSE, standardize = TRUE, intercept = TRUE, 
                                             parallel.boot = FALSE, ncores.boot = 1, ...)
# generate the data
set.seed(2015)
n <- 200      # number of obs
p <- 500
s <- 10
beta <- rep(0, p)
beta[1:s] <- runif(s, 1/3, 1)
x <- rmvnorm(n = n, mean = rep(0, p), method = "svd")
signal <- sqrt(mean((x %*% beta)^2))
sigma <- as.numeric(signal / sqrt(10))  # SNR=10
y <- x %*% beta + rnorm(n)

#run the residual bootstrap Lasso
set.seed(0)
obj <- bootLasso(x = x, y = y, B = 10)
# confidence interval
obj$interval
sum((obj$interval[1,]<=beta) & (obj$interval[2,]>=beta))

X$IncarcerationStats <- Y$IncarcerationStats
```
